### ISSUE TITLE
replace JHU specific locatorId types with universal types

### ISSUE THREAD

**Issue by jrmartino** [eclipse-pass/pass-authz#91]
#90 

currently, JHU User locatorIds have types employeeid, hopkinsid and jhed. we should be using names which identify these types in a more universal way, so replaces hopkinsid type with unique-id, and  jhed type with eppn. this simplifies implementing PASS for other institutions.

changes need to be made in the sign-up/login process, as well as in any loader/service which creates, updates  or looks for existing users, to write the new type strings to locatorIds.

care needs to be taken that we do not lose the ability to resolve existing users. since the employeeid type is being retained,  the lookup of any user having an employee id type should still work. 

twp possible approaches, both invovling updates to the user service and grant loader 

- the brute force way of dealing with this change for JHU instances would be to run an update script against all users, and updating the type strings, 
Pro: all the data would be consistent with the new naming scheme
Con: requires running an update script against all users in each instance during a maintenance window
 
 
- a less invasive fix would be to locate all users in these instances who do not have an employeeid locatorId set, and update their locatorId types to  eppn and unique-id. all future updates to users would use the new type names.   
Pro: requires only looking for users in existing systms which do not have employeeid set, and updating their locatorIds manually
Con: leaves most users with inconsistent-looking data, which might be confusing from a maintenence standpoint down the road

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete. This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
